from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editList(object):
    def regMain(self):
        from regMain import Ui_regMain
        self.regmain = QtWidgets.QDialog()
        self.ui = Ui_regMain()
        self.ui.setupUi(self.regmain)
        self.regmain.show()

    def setupUi(self, editList):
        editList.setObjectName("editList")
        editList.resize(480, 800)
        font = QtGui.QFont()
        font.setPointSize(9)
        editList.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(editList)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 421, 661))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.label = QtWidgets.QLabel(editList)
        self.label.setGeometry(QtCore.QRect(120, 10, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back = QtWidgets.QPushButton(editList, clicked = lambda: self.regMain())
        self.back.setGeometry(QtCore.QRect(20, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.back.clicked.connect(editList.close)
        self.retranslateUi(editList)
        QtCore.QMetaObject.connectSlotsByName(editList)

    def retranslateUi(self, editList):
        _translate = QtCore.QCoreApplication.translate
        editList.setWindowTitle(_translate("editList", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("editList", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("editList", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("editList", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("editList", "Emp Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("editList", "Emp ID"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("editList", "ABC"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("editList", "123"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("editList", "XYZ"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("editList", "456"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("editList", "MNO"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("editList", "789"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("editList", "<html><head/><body><p align=\"center\">Edit Info</p></body></html>"))
        self.back.setText(_translate("editList", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editList = QtWidgets.QDialog()
    ui = Ui_editList()
    ui.setupUi(editList)
    editList.show()
    sys.exit(app.exec_())
