from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewList(object):
    def regMain(self):
        from regMain import Ui_regMain
        self.regmain = QtWidgets.QDialog()
        self.ui = Ui_regMain()
        self.ui.setupUi(self.regmain)
        self.regmain.show()

    def setupUi(self, viewList):
        viewList.setObjectName("viewList")
        viewList.resize(480, 800)
        self.label = QtWidgets.QLabel(viewList)
        self.label.setGeometry(QtCore.QRect(130, 10, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(viewList)
        self.tableWidget.setGeometry(QtCore.QRect(20, 100, 451, 661))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        self.back = QtWidgets.QPushButton(viewList, clicked = lambda: self.regMain())
        self.back.setGeometry(QtCore.QRect(20, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.back.clicked.connect(viewList.close)
        self.retranslateUi(viewList)
        QtCore.QMetaObject.connectSlotsByName(viewList)

    def retranslateUi(self, viewList):
        _translate = QtCore.QCoreApplication.translate
        viewList.setWindowTitle(_translate("viewList", "Dialog"))
        self.label.setText(_translate("viewList", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">View Info</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("viewList", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("viewList", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("viewList", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("viewList", "Emp Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("viewList", "Emp ID"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("viewList", "ABC"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("viewList", "123"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("viewList", "XYZ"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("viewList", "456"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("viewList", "MNO"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("viewList", "789"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.back.setText(_translate("viewList", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewList = QtWidgets.QDialog()
    ui = Ui_viewList()
    ui.setupUi(viewList)
    viewList.show()
    sys.exit(app.exec_())
