# -*- coding: utf-8 -*-
"""createDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4fyLr1NpVkNthnbbpYHY-e9Ri7bqcPt
"""

import sqlite3
import datetime 
conn = sqlite3.connect('localdb.db')
curs = conn.cursor()
print ("Opened database successfully");

curs.execute('''CREATE TABLE IF NOT EXISTS employees (
            emp_id INTEGER PRIMARY KEY,
            EmpName TEXT NOT NULL,
            Department TEXT NOT NULL
        )''')

#define tables
# Define the foreign key constraints
curs.execute('''CREATE TABLE IF NOT EXISTS admin (
                 admin_id INTEGER ,
                 emp_id INTEGER,
                 FOREIGN KEY (emp_id)
                 REFERENCES employees(emp_id)
             )''')

curs.execute('''CREATE TABLE IF NOT EXISTS faceid (
                 emp_id INTEGER ,
                 face_id INTEGER,
                 FOREIGN KEY (emp_id)
                 REFERENCES employees(emp_id)
             )''')

curs.execute('''CREATE TABLE IF NOT EXISTS fingerprinttag (
                 fingerprint_tag INTEGER ,
                 emp_id INTEGER,
                 FOREIGN KEY (emp_id)
                 REFERENCES employees(emp_id)
             )''')

curs.execute('''CREATE TABLE IF NOT EXISTS rfid (
                 rf_id INTEGER ,
                 emp_id INTEGER,
                 FOREIGN KEY (emp_id)
                 REFERENCES employees(emp_id)
             )''')

curs.execute('''CREATE TABLE IF NOT EXISTS checkin(
                  emp_id INTEGER,
                  check_in TIMESTAMP,
                  FOREIGN KEY (emp_id)
                  REFERENCES employees(emp_id))''')

curs.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = curs.fetchall()

# Print the table names
for table in tables:
    print(table[0])

curs.execute("PRAGMA table_info(rfid)")
table_info = curs.fetchall()


for column in table_info:
    print(column[1] , column[2])