# -*- coding: utf-8 -*-
"""sensordata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17luh3EAIpdBoKlZVbKA6cZ6TAF_kQQVJ
"""

import sqlite3
#import adafruit_fingerprint

conn = sqlite3.connect('localdb.db')
curs = conn.cursor()
print ("Opened database successfully");

"""For taking tag and emp_id from csv file and inserting into table"""

import csv

# open the file
file_path='/content/finger.csv'
with open(file_path, 'r') as csvfile:
    # create the object of csv.reader()
    csv_file_reader = csv.reader(csvfile, delimiter=',')
    for row in csv_file_reader:
        
        for i in range(len(row)):
            # assign each field its value
            emp_id=row[0]
            fingerprint_tag=row[1]
            
            InsertQuery=(f"INSERT INTO fingerprinttag VALUES ('{emp_id}','{fingerprint_tag}')")
        # 6. Execute query
        curs.execute(InsertQuery)

curs.execute('''CREATE TABLE fingerprinttag
             (emp_id INTEGER,
              fingerprint_tag INTEGER
              )''')

sql=('''SELECT * FROM fingerprinttag  ''')

curs.execute(sql)
curs.fetchall()

"""For finger print tag from sensor to fingerprint table"""

#Take tag value from the sensor with the emp_id
def insert_fingerprint_tag(emp_id, id_value):
  # Initialize the serial connection to the fingerprint sensor
    uart = serial.Serial("/dev/ttyUSB0", baudrate=57600, timeout=1)

    # Initialize the fingerprint sensor object
    fingerprint = adafruit_fingerprint.Adafruit_Fingerprint(uart)

    # Wait for the fingerprint sensor to be ready
    while not fingerprint.is_ready():
        pass

    # Wait for a finger to be detected
    while not fingerprint.get_image():
        pass

    # Convert the fingerprint image to a template
    fingerprint_image = fingerprint.image2Tz()
    template_id = fingerprint.store_template()

    # Get the fingerprint tag value
    tagm_value = str(template_id)

    # Get the emp_id from the user input
   # emp_id = Take input from hardware

    # Connect to the database
    conn = sqlite3.connect('localdb.db')

    # Create a cursor object
    curs = conn.cursor()


#insert into the finger table
  
    curs.execute("INSERT INTO fingerprinttag (emp_id, tagvalue) VALUES (?, ?)", (emp_id, id_value))

 

    # Print a message to confirm that the fingerprint tag value has been saved
    print("Fingerprint tag value saved for emp_id:", emp_id,id_value)